-- 1
SELECT name FROM CUSTOMER WHERE flag IS NOT NULL;
-- 2
SELECT model FROM SCOOTER WHERE availability = 'YES';
-- 3
SELECT SCOOTER.model, SCOOTER.manufacturer, CUSTOMER.name, RENTAL.dueDate
FROM SCOOTER
INNER JOIN RENTAL ON RENTAL.model = SCOOTER.model
INNER JOIN CUSTOMER ON RENTAL.customerID = CUSTOMER.customerID
WHERE RENTAL.returnDate IS NULL ORDER BY RENTAL.duedate desc;
-- 4
SELECT SCOOTER.model, SCOOTER.manufacturer, CUSTOMER.name
FROM SCOOTER
INNER JOIN RENTAL ON NOW() > RENTAL.dueDate AND returnDate IS NUll
INNER JOIN CUSTOMER ON CUSTOMER.customerID = RENTAL.customerID
WHERE RENTAL.model = SCOOTER.model;
-- 5
SELECT CUSTOMER.name, COUNT(*) 
	FROM CUSTOMER 
	INNER JOIN REFFERALS ON REFFERALS.customerID = CUSTOMER.customerID
	GROUP BY CUSTOMER.name
	ORDER BY COUNT(*) desc
	LIMIT 5;
-- 6
SELECT * FROM RENTAL WHERE 1 = RENTAL.customerID ORDER BY borrowDate;
-- 7
SELECT addFees, notes 
	FROM RENTAL 
	WHERE 1 = RENTAL.customerID AND 56 = RENTAL.model 
	AND date '1999-01-08' + interval '0 hour' = RENTAL.borrowDATE;
-- 8
SELECT DISTINCT manufacturer FROM SCOOTER;
